CREATE VIEW BOOKS_AND_READERS AS
SELECT RD.READER_ID, RD.FIRSTNAME, RD.LASTNAME, BK.TITLE, RT.RENT_DATE, RT.RETURN_DATE
FROM READERS RD,
     BOOKS BK,
     RENTS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
  AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;

SELECT * FROM BOOKS_AND_READERS;


SELECT * FROM BOOKS_AND_READERS
    WHERE RENT_DATE > DATE_SUB(CURDATE(),INTERVAL 5 DAY);

#-----EVENTS---

SHOW PROCESSLIST;

# SET GLOBAL EVENT_SCHEDULER=ON;

USE kodilla_course;           -- [1]
CREATE EVENT UPDATE_VIPS      -- [2]
    ON SCHEDULE EVERY 1 MINUTE -- [3]
    DO CALL UpdateVipLevels(); -- [4]

DROP EVENT UPDATE_VIPS;

UPDATE readers
SET VIP_LEVEL = 'Not set';

SELECT * FROM readers;