#----TABLE----
CREATE TABLE STATS
(
    STAT_ID   INT(11) AUTO_INCREMENT,
    STAT_DATE DATETIME    NOT NULL,
    STAT      VARCHAR(20) NOT NULL,
    VALUE     INT(11)     NOT NULL,
    PRIMARY KEY (STAT_ID)
);

#-----VIEW------
CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS NUMBER_OF_BESTSELLERS
FROM BOOKS
WHERE BESTSELLERS = TRUE;

#-----EVENT------
DELIMITER $$
USE kodilla_course;
CREATE EVENT UPDATE_BESTSELLERS
    ON SCHEDULE EVERY 1 MINUTE
    DO
    BEGIN
        CALL UpdateBestSellers();

        INSERT INTO STATS(STAT_DATE, STAT, VALUE)
            VALUE (CURTIME(), 'BESTSELLERS', (SELECT * FROM BESTSELLERS_COUNT));
    END $$
DELIMITER ;

#---CHECK RESULTS
SELECT * FROM BESTSELLERS_COUNT;
SELECT * FROM STATS;

# REMOVE EVENT
# DROP EVENT UPDATE_BESTSELLERS;