EXPLAIN  SELECT COUNT(*)
         FROM READERS
         WHERE FIRSTNAME = 'John';

CREATE INDEX FIRST_AND_LAST_NAME_NO ON READERS (FIRSTNAME, LASTNAME);

EXPLAIN  SELECT COUNT(*)
         FROM READERS
         WHERE FIRSTNAME = 'John';


EXPLAIN  SELECT COUNT(*)
         FROM BOOKS
         WHERE TITLE = 'The Trial';

CREATE INDEX TITLENO ON BOOKS (TITLE);

EXPLAIN  SELECT COUNT(*)
         FROM BOOKS
         WHERE TITLE = 'The Trial';